### ISSUE TITLE
Wrong Flags for reading registry with only ReadOnly_Access

### ISSUE THREAD

**Issue by TOchse** [X-Sharp/FabTools#2]
When trying to read from Registry with ReadOnly set to TRUE, the first Flag set is STANDARD_RIGHTS_ALL.
It should be set to STANDARD_RIGHTS_READ.
Otherwise Application without admin rights can't access the registry.
So this:

>ACCESS KEY_READ_ACCESS AS DWORD PASCAL
RETURN _AND( _OR( STANDARD_RIGHTS_ALL,;
KEY_QUERY_VALUE,;
KEY_ENUMERATE_SUB_KEYS,;
KEY_NOTIFY ), _NOT( SYNCHRONIZE ) )

Should be changed to:

>ACCESS KEY_READ_ACCESS AS DWORD PASCAL 
RETURN 	_AND( _OR( STANDARD_RIGHTS_READ,;
KEY_QUERY_VALUE,	;
KEY_ENUMERATE_SUB_KEYS,;
KEY_NOTIFY ), _NOT( SYNCHRONIZE ) )

**Comment by FabForay** [comment]
Hi,
sorry for the silent... I didn't receive a notification for your issue, and (my bad) I'm not looking very often for these on the repo ;)
You are right, there is something wrong there.
I will update with your indications asap.

**Comment by fforay** [comment]
Done
