### ISSUE TITLE
Height and width in StretchDraw methods

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/FabTools#4]
Hello,

FabTools/FabTools/FabPaintLib/FabPaintLib.prg

In StretchDraw and StretchDrawDC, the width and height values were added with the x and y position values.
I think this is the reason why it is not displaying correctly, if I change it without the extra values it is ok.

**Comment by fforay** [comment]
Hi Christian,
so you mean that :
SELF:ShowDC( hDC, x, y, x+w, y+h )
Should be
SELF:ShowDC( hDC, x, y, w, h )

Right ?
Thanks for the information.

I will correct it.

**Comment by christianschmid200272** [comment]
Hi Fabrice,
yes right, from
SELF:ShowDC( hDC, x, y, x+w, y+h )
in my opinion should be
SELF:ShowDC( hDC, x, y, w, h )
become.
